const fileActionTypes  = ({
  SET_FILES_START : 'SET_FILES_START',
  SET_FILES_SUCCESS : 'SET_FILES_SUCCESS',
  SET_FILES_FAILURE : 'SET_FILES_FAILURE', 

  SET_FILES_STORAGE_FILTER : 'SET_FILES_STORAGE_FILTER',
  UPDATE_FILES_AFTER_FILTERING : 'UPDATE_FILES_AFTER_FILTERING',
  MAKE_FOLDER : 'MAKE_FOLDER',
  REMOVE_FILE_ITEM : 'REMOVE_FILE_ITEM',
  CLEAR_FILES : 'CLEAR_FILES',
  UPDATE_FILES: 'UPDATE_FILES',
  IS_PROCESSING : 'IS_PROCESSING',

  FETCH_FILES_START : 'FETCH_FILES_START',
  FETCH_FILES_SUCCESS : 'FETCH_FILES_SUCCESS',
  FETCH_FILES_FAILURE : 'FETCH_FILES_FAILURE',
});

export default fileActionTypes;