const fileActionTypes  = ({
  IMPORT_FILES_START : 'IMPORT_FILES_START',
  IMPORT_FILES_SUCCESS : 'IMPORT_FILES_SUCCESS',
  IMPORT_FILES_FAILURE : 'IMPORT_FILES_FAILURE', 

  SET_FILES_STORAGE_FILTER : 'SET_FILES_STORAGE_FILTER',
  REMOVE_FILE_ITEM : 'REMOVE_FILE_ITEM',
  CLEAR_FILES : 'CLEAR_FILES',
  UPDATE_FILES: 'UPDATE_FILES',
  IS_PROCESSING : 'IS_PROCESSING',

  FETCH_FILES_START : 'FETCH_FILES_START',
  FETCH_FILES_SUCCESS : 'FETCH_FILES_SUCCESS',
  FETCH_FILES_FAILURE : 'FETCH_FILES_FAILURE',

  MAKE_FOLDER_START : 'MAKE_FOLDER_START',
  MAKE_FOLDER_SUCCESS : 'MAKE_FOLDER_SUCCESS',
  MAKE_FOLDER_FAILURE : 'MAKE_FOLDER_FAILURE',

  SET_FILES : 'SET_FILES',

  FETCH_FILTERED_FILES_START : 'FETCH_FILTERED_FILES_START',
  FETCH_FILTERED_FILES_SUCCESS : 'FETCH_FILTERED_FILES_SUCCESS',
  FETCH_FILTERED_FILES_FAILURE : 'FETCH_FILTERED_FILES_FAILURE',
});

export default fileActionTypes;